/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.Gson;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void apiTesting() throws IOException {
        String url = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        HttpURLConnection connect = (HttpURLConnection) new URL(url).openConnection();


        connect.setRequestMethod("GET");
        connect.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");

        int resCode = connect.getResponseCode();
        if (resCode == HttpURLConnection.HTTP_OK) {
            InputStreamReader inputStreamReader = new InputStreamReader(connect.getInputStream());
            BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
            String data = bufferedReader.readLine();
            bufferedReader.close();
            Gson gson = new Gson();
            Quotes ownQuote = gson.fromJson(data, Quotes.class);
            String findAuther = ownQuote.author;
            String findQuote = ownQuote.content;


            System.out.println("Results From API:");
            System.out.println("Author: " + findAuther);
            System.out.println("Quote: " + findQuote);

        }
    }
}
