/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.Gson;

import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        ReadAFile read=new ReadAFile();
        read.readFile("./app/src/main/resources/recentquotes.json");

        Scanner myObj = new Scanner(System.in);  // Create a Scanner object
        System.out.println("Enter author name");
        read.readFile("./app/src/main/resources/recentquotes.json",myObj.nextLine());

        Scanner myObj2 = new Scanner(System.in);  // Create a Scanner object
        System.out.println("Enter quote or a word from quote");
        read.findQuote("./app/src/main/resources/recentquotes.json",myObj2.nextLine());



    }

}
